CREATE TABLE auth_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255),
    refresh_token VARCHAR(500)
);

CREATE UNIQUE INDEX ux_auth_user_username ON auth_user (username);
